
[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
ap_iprogram = "79VSBMCvvTKNwZSocidYCTxDEDqy39ge9fdzWiBcP5WV"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/new_program_id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

